[build]
  base = "."
  command = "flutter build web --release --web-renderer html"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "3.24.0"
  FLUTTER_BUILD_MODE = "release"
  FLUTTER_WEB_USE_SKIA = "false"

# Cache Flutter SDK and dependencies
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# SPA redirect rules for Flutter Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for performance and security
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-flutter"