[build]
  command = "flutter build web --release"
  publish = "build/web"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Caching policies
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Existing headers can be added here as needed
