# Production Netlify configuration for Zeeky Social
# For development-specific configuration, see netlify.dev.toml

[build]
  base = "."
  command = "flutter build web --release --web-renderer html"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "3.24.0"
  FLUTTER_BUILD_MODE = "release"
  FLUTTER_WEB_USE_SKIA = "false"
  NODE_ENV = "production"
  
  # Production Firebase Configuration (use environment variables)
  FIREBASE_API_KEY = "${FIREBASE_API_KEY}"
  FIREBASE_AUTH_DOMAIN = "${FIREBASE_AUTH_DOMAIN}"
  FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
  FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
  FIREBASE_MESSAGING_SENDER_ID = "${FIREBASE_MESSAGING_SENDER_ID}"
  FIREBASE_APP_ID = "${FIREBASE_APP_ID}"

# Cache Flutter SDK and dependencies
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# SPA redirect rules for Flutter Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for performance and security
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Plugin configuration for production
[[plugins]]
  package = "@netlify/plugin-flutter"
  
  [plugins.inputs]
    version = "3.24.0"
    cache = true

# Production environment contexts
[context.production]
  command = "flutter build web --release --web-renderer html"
  
  [context.production.environment]
    NODE_ENV = "production"
    FLUTTER_BUILD_MODE = "release"

[context.deploy-preview]
  command = "flutter build web --profile --web-renderer html"
  
  [context.deploy-preview.environment]
    NODE_ENV = "staging"
    FLUTTER_BUILD_MODE = "profile"

# Functions configuration for production
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"