name: zeeky_social
description: "A hybrid social media and messaging platform."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  provider: ^6.1.2

  # Environment configuration
  flutter_dotenv: ^5.1.0

  # Firebase Backend Services
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.1
  firebase_app_check: ^0.3.0
  firebase_ai: ^0.5.1
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0

  # UI & Utilities
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Environment files
  assets:
    - .env.dev
