// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6N1O6feQjTNhWqAIh3QZ71m7qvx9pqSE',
    appId: '1:961063588565:web:0857f2508591e3f185c85c',
    messagingSenderId: '961063588565',
    projectId: 'gen-lang-client-0610030211',
    authDomain: 'gen-lang-client-0610030211.firebaseapp.com',
    storageBucket: 'gen-lang-client-0610030211.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtQTL3-egsBm5xKkDpYBR-VdyHTeHVQ4',
    appId: '1:961063588565:android:83bf87b7457e81b285c85c',
    messagingSenderId: '961063588565',
    projectId: 'gen-lang-client-0610030211',
    storageBucket: 'gen-lang-client-0610030211.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMCpmSCBmVb4OjG9Mp6POu2DDQkxF9zoI',
    appId: '1:961063588565:ios:7eac9ed45f6be66f85c85c',
    messagingSenderId: '961063588565',
    projectId: 'gen-lang-client-0610030211',
    storageBucket: 'gen-lang-client-0610030211.firebasestorage.app',
    iosBundleId: 'com.example.my',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCpmSCBmVb4OjG9Mp6POu2DDQkxF9zoI',
    appId: '1:961063588565:ios:eeb532226e716b3685c85c',
    messagingSenderId: '961063588565',
    projectId: 'gen-lang-client-0610030211',
    storageBucket: 'gen-lang-client-0610030211.firebasestorage.app',
    iosBundleId: 'com.example.myap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6N1O6feQjTNhWqAIh3QZ71m7qvx9pqSE',
    appId: '1:961063588565:web:004dd64d7291ef5a85c85c',
    messagingSenderId: '961063588565',
    projectId: 'gen-lang-client-0610030211',
    authDomain: 'gen-lang-client-0610030211.firebaseapp.com',
    storageBucket: 'gen-lang-client-0610030211.firebasestorage.app',
  );

}